// Generates src/abis.ts from the Foundry build output (contracts/out), so the ABIs used off-chain cannot drift
// from the contracts. Run after `forge build`: pnpm --filter @kanda/chain gen:abis
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../../../contracts/out');

/** Export name -> [source file, contract name] in contracts/out. */
export const SOURCES = {
  kandaTokenAbi: ['KandaToken.sol', 'KandaToken'],
  participantRegistryAbi: ['ParticipantRegistry.sol', 'ParticipantRegistry'],
  basketVaultAbi: ['BasketVault.sol', 'BasketVault'],
  timelockControllerAbi: ['TimelockController.sol', 'TimelockController'],
  erc20MetadataAbi: ['IERC20Metadata.sol', 'IERC20Metadata'],
};

export function readAbi(file, contract) {
  return JSON.parse(readFileSync(join(out, file, `${contract}.json`), 'utf8')).abi;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const parts = [
    '// Generated by scripts/gen-abis.mjs from contracts/out. Do not edit; re-run after changing a contract.',
    '',
  ];
  for (const [name, [file, contract]] of Object.entries(SOURCES)) {
    parts.push(`export const ${name} = ${JSON.stringify(readAbi(file, contract), null, 2)} as const;`, '');
  }
  writeFileSync(join(here, '../src/abis.ts'), parts.join('\n'));
  process.stdout.write(`Wrote ${Object.keys(SOURCES).length.toString()} ABIs to src/abis.ts\n`);
}
